### ISSUE TITLE
struct

### ISSUE THREAD

**Issue by PavelTajdus** [zeitgeist87/RFTransmitter#1]
Hello,
is there some way, how to send multiple data as struct? Im Arduino newbie, so i dont get all the stuff about data types and how to send data, and struct is nice and simple way to send multiple data.

**Comment by zeitgeist87** [comment]
Hi @PavelTajdus,

Sure you can send any type of data. You just have to cast it into a byte pointer like this:

```cpp
struct MyData {
    int value;
    int value2;
    byte buffer[200];
};

void loop() {
  struct MyData data;
  data.value = 2;
  data.value2 = 5;

  transmitter.send((byte *)data, sizeof(data));
}
```

**Comment by PavelTajdus** [comment]
Thank you.
