### ISSUE TITLE
Library too large

### ISSUE THREAD

**Issue by mrohner** [zeitgeist87/RFTransmitter#2]
I liked the idea of forward correction and wanted to test on an ATTINY13. Unfortunately the library is too large for this microprocessor. Any idea where to save program space?

**Comment by zeitgeist87** [comment]
The ATTINY13 is extremely limited. Even if you could fit the library, it does not have enough SRAM to run it. The ATTINY13 has 64 bytes of SRAM. I tried to implement a simple button on it with a C++ class and the stack silently overwrote the heap and corrupted my data structures. I don't think it is possible without a highly optimized rewrite without C++ classes.

Sorry for the late reply, I am currently extremely busy at my day job.

**Comment by zeitgeist87** [comment]
Rewriting it for the ATTINY13 would be an interesting project, though...
